name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish Windows Release build
        run: dotnet publish MSCS.csproj -c Release -r win-x64 --self-contained false -o publish

      - name: Upload release asset
        uses: ncipollo/release-action@v1
        with:
          artifacts: publish/MSCS.exe
          artifactErrorsFailBuild: true
          tag: 'master-${{ github.run_number }}'
          name: 'Main build ${{ github.run_number }}'
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}