name: Build and Release (Single EXE)

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine build version
        shell: pwsh
        run: |
          $version = "1.0.${{ github.run_number }}"
          $assemblyVersion = "$version.0"
          "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "ASSEMBLY_VERSION=$assemblyVersion" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          "RELEASE_TAG=v$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore

      - name: Publish self-contained single-file
        run: >
          dotnet publish MSCS.csproj
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeAllContentForSelfExtract=true
          -p:EnableCompressionInSingleFile=true
          -p:PublishTrimmed=false
          -o publish
          -p:Version=${{ env.VERSION }}
          -p:FileVersion=${{ env.ASSEMBLY_VERSION }}
          -p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }}

      - name: Rename EXE
        shell: pwsh
        run: |
          $exe = Get-ChildItem publish\*.exe | Select-Object -First 1
          Rename-Item $exe.FullName MSCS-win-x64.exe

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: publish/MSCS-win-x64.exe
          artifactErrorsFailBuild: true
          tag: ${{ env.RELEASE_TAG }}
          name: MSCS ${{ env.VERSION }}
          generateReleaseNotes: true
          makeLatest: true
          token: ${{ secrets.GITHUB_TOKEN }}
